# - name: Reload nginx configuration
#   become: true
#   become_user: "{{ project_user_name }}"
#   become_method: ansible.builtin.su
#   community.docker.docker_container_exec:
#     name: "{{ nginx_container_name }}"
#     command: nginx -s reload

- name: Run docker compose
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: present
    profiles: run
  environment:
    CERT_DOMAIN: "{{ letsencrypt_domain }}"
