- name: Enable cron service
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.service:
    name: "{{ cron_service | default('crond') }}"
    state: started
    enabled: true

- name: Reload nginx configuration
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  community.docker.docker_container_exec:
    name: "{{ nginx_container_name }}"
    command: nginx -s reload
