---

- name: Set up new machines
  hosts: all
  roles:
    - system
    - docker
    - harden
  tags: always

- name: Download and run project
  hosts: all
  roles:
    - github
    - scific
  tags: run
