---

- name: Download mage-docker project from GitHub
  hosts: virt
  vars:
    keyfile_path: '~/.ssh/github'
    project_dir: '~/mage-docker'
    docker_repo: git@github.com:wadofan/mage-docker.git
    scific_repo: https://github.com/scific-conference/scific.git
  become: true
  become_user: '{{ docker_user }}'
  become_method: ansible.builtin.su
  tasks:

    - name: Check if needed packages are installed
      ansible.builtin.package:
        name:
          - git
          - openssh
        state: present

    - name: Check if SSH key exist
      ansible.builtin.stat:
        path: '{{ keyfile_path }}'
      register: sshkey

    - name: Copy SSH key for GitHub (if not exist)
      ansible.builtin.copy:
        src: ./keys/github
        dest: '{{ keyfile_path }}'
        mode: '0600'
      when: not sshkey.stat.exists

    - name: Clone repository from GitHub
      ansible.builtin.git:
        key_file: '{{ keyfile_path }}'
        accept_hostkey: true
        repo: '{{ docker_repo }}'
        dest: '{{ project_dir }}'
        version: main
        single_branch: true

    - name: Clone SCIFiC repository
      ansible.builtin.git:
        repo: '{{ scific_repo }}'
        dest: '{{ project_dir }}/scific'
        single_branch: true

# - name: Start project
#   hosts: virt
#   become: true
#   become_user: '{{ docker_user }}'
#   become_method: ansible.builtin.su
#   tasks:

#     - name: Run docker compose
#       ansible.builtin.shell: 
#         chdir: ~/mage-docker
#         cmd: docker compose up -d
