---

- name: Check if needed tools are installed
  hosts: all
  become: true
  become_method: ansible.builtin.sudo
  pre_tasks:

    - name: When OS is from Debian family
      ansible.builtin.apt:
        name:
          - git
          - openssh-client
        state: present
      when: ansible_facts['os_family'] == "Debian"

    - name: When OS is from RedHat family (untested)
      ansible.builtin.dnf:
        name:
          - git
          - openssh
        state: present
      when: ansible_facts['os_family'] == "RedHat"

    - name: When OS is Alpine Linux (untested)
      community.general.apk:
        name: git,openssh
        state: present
      when: ansible_facts['os_family'] == "Alpine"

    - name: When OS is from SUSE family (untested)
      community.general.zypper:
        name:
          - git-core
          - openssh
        state: present
      when: ansible_facts['os_family'] == "Suse"

    - name: When OS is is based on Arch (untested)
      community.general.pacman:
        name:
          - git
          - openssh
        state: present
      when: ansible_facts['os_family'] == "Archlinux"

    - name: When OS is based on Gentoo (untested)
      community.general.portage:
        package:
          - dev-vcs/git
          - net-misc/openssh
        state: present
      when: ansible_facts['os_family'] == "Gentoo"

    - name: When OS is FreeBSD (untested)
      community.general.pkgng:
        name:
          - git
          - openssh
      when: ansible_facts['os_family'] == "FreeBSD"

    - name: When OS is NetBSD (untested)
      community.general.pkgin:
        name: git,openssh
        # devel/git
        # (https://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/devel/git/index.html)
        # security/openssh
        # (https://ftp.netbsd.org/pub/pkgsrc/current/pkgsrc/security/openssh/index.html)
        state: present
      when: ansible_facts['os_family'] in "NetBSD"

    - name: When OS is OpenBSD (untested)
      community.general.openbsd_pkg:
        name:
          - git # devel/git (https://openbsd.app/path/devel/git)
          # openssh (https://www.openssh.com/openbsd.html)
        state: present
      when: ansible_facts['os_family'] == "OpenBSD"

    # - name: When OS is based on Mandrake (untested)
    #   when: ansible_facts['os_family'] == "Mandrake"

    # - name: When OS is Solaris (untested)
    #   when: ansible_facts['os_family'] == "Solaris"

- name: Download and run project from GitHub
  hosts: all
  vars:
    keyfile_path: "~/.ssh/github"
    project_dir: "~/mage-docker"
    project_repo: "git@github.com:wadofan/mage-docker.git"
    scific_repo: "https://github.com/scific-conference/scific.git"
  tasks:

    - name: Check if SSH key exist
      ansible.builtin.stat:
        path: "{{ keyfile_path }}"
      register: sshkey

    - name: Copy SSH key for GitHub (if not exist)
      ansible.builtin.copy:
        src: ../keys/github
        dest: "{{ keyfile_path }}"
        mode: '0600'
      when: not sshkey.stat.exists

    - name: Clone repository from GitHub
      ansible.builtin.git:
        key_file: "{{ keyfile_path }}"
        accept_hostkey: true
        repo: "{{ project_repo }}"
        dest: "{{ project_dir }}"
        version: main
        single_branch: true

    - name: Clone SCIFiC repository
      ansible.builtin.git:
        repo: "{{ scific_repo }}"
        dest: "{{ project_dir }}/scific"
        version: main
        single_branch: true

    - name: Run docker compose to start project
      community.docker.docker_compose_v2:
        state: present
        project_src: "{{ project_dir }}"
        build: always
        pull: missing
