- name: copy SSH key to acces GitHub repositories
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  ansible.builtin.copy:
    src: "{{ local_keyfile }}"
    dest: "{{ remote_keyfile }}"
    mode: '0600'

- name: clone project repository
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  ansible.builtin.git:
    key_file: "{{ remote_keyfile }}"
    accept_hostkey: true
    repo: "{{ project_repo }}"
    dest: "{{ project_dir }}"
    version: main
    single_branch: true

- name: clone website repository
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  ansible.builtin.git:
    repo: "{{ website_repo }}"
    dest: "{{ project_dir }}/webroot"
    version: main
    single_branch: true
