- name: Restart SSH service
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.service:
    name: "{{ ssh_service | default('sshd') }}"
    state: restarted

- name: Enable firewall
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  community.general.ufw:
    state: enabled
    logging: 'on'

- name: Disable root login
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.user: 
    name: root
    password: '!'
    shell: /usr/bin/nologin
