- name: Enable docker service
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add user to docker group
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.user:
    name: "{{ project_user_name }}"
    groups: docker
    append: true
