---

mage_user_name: "{{ lookup('env', 'MAGE_USER', default='mage') }}"
mage_user_pass: "{{ lookup('env', 'MAGE_PASS', default='changeme') }}"
mage_user_key: "{{ lookup('file', '~/.ssh/mage.pub') }}"
mage_user_shell: "{{ lookup('env', 'MAGE_SHELL', default='/usr/bin/bash') }}"

project_dir: "/home/{{ mage_user_name }}/project"

letsencrypt_email: "{{ lookup('env', 'MAGE_EMAIL') }}"
letsencrypt_domain: "{{ lookup('env', 'MAGE_DOMAIN') }}"
