---

project_user_name: "{{ lookup('env', 'MAGE_USER', default='mage') }}"
project_user_pass: "{{ lookup('env', 'MAGE_PASS', default='changeme') }}"
project_user_shell: "{{ lookup('env', 'MAGE_SHELL',default='/usr/bin/bash') }}"
project_user_key: "{{ lookup('file', '~/.ssh/mage.pub') }}"

project_dir: "/home/{{ project_user_name }}/project"

letsencrypt_email: "{{ lookup('env', 'MAGE_EMAIL') }}"
letsencrypt_domain: "{{ lookup('env', 'MAGE_DOMAIN') }}"

