---

project_user_name: "mage"
project_user_pass: "{{ lookup('env', 'MAGE_PASS') }}"
project_user_shell: "/usr/bin/bash"
project_user_key: "{{ lookup('file', '~/.ssh/mage.pub') }}"
project_dir: "/home/{{ project_user_name }}/project"
