- name: clone project repository
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  ansible.builtin.git:
    key_file: "{{ remote_keyfile }}"
    accept_hostkey: true
    repo: "{{ project_repo }}"
    dest: "{{ project_dir }}"
    update: yes
    version: main
    single_branch: true

- name: clone website repository
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  ansible.builtin.git:
    repo: "{{ website_repo }}"
    dest: "{{ project_dir }}/webroot"
    update: yes
    version: main
    single_branch: true

