---

- name: Prepare system to download and run project
  ansible.builtin.include_tasks: prepare.yml

- name: Download project from GitHub
  ansible.builtin.include_tasks: github.yml

- name: Use newly generated certificates
  ansible.builtin.include_tasks: cert.yml

