---

- name: Prepare system to download and run project
  ansible.builtin.include_tasks: prepare.yml

- name: Clone repositories from GitHub
  ansible.builtin.include_tasks: clone.yml

- name: Run Docker project
  ansible.builtin.include_tasks: run.yml
