- name: make sure that needed packages are installed
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - "{{ git_pkg | default('git') }}"
      - "{{ ssh_pkg | default('openssh') }}"
    state: present

- name: copy SSH key to acces GitHub repositories
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  ansible.builtin.copy:
    src: "{{ local_keyfile }}"
    dest: "{{ remote_keyfile }}"
    mode: '0600'
