- name: Make sure that needed packages are installed
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - "{{ git_pkg | default('git') }}"
      - "{{ ssh_pkg | default('openssh') }}"
      - "{{ cron_pkg | default('cron') }}"
    state: present
  notify: Enable cron service

- name: Create user to run docker project
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.user:
    name: "{{ docker_user_name }}"
    password: "{{ docker_user_pass | password_hash('sha512') }}"
    comment: SCIFiC
    groups: docker,sudo
    append: true
    create_home: true

- name: Generate cron jobs file from template
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.template:
    src: crontab
    dest: /etc/cron.d/scific
    owner: root
    group: root
    mode: '0644'

- name: Add SSH key to access "{{ docker_user_name }}"
  become: true
  become_user: "{{ docker_user_name }}"
  become_method: ansible.builtin.su
  ansible.posix.authorized_key:
    user: "{{ docker_user_name }}"
    key: "{{ docker_user_key }}"
    state: present
