- name: run docker compose to generate certificates
  become: true
  become_user: "{{ mage_user_name }}"
  become_method: ansible.builtin.su
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: present
    profiles: gen
  environment:
    EMAIL: "{{ letsencrypt_email }}"
    DOMAIN: "{{ letsencrypt_domain }}"
  ignore_errors: true

- name: wait until container stops
  ansible.builtin.wait_for:
    timeout: 10
#    port: 80
#    state: stopped

- name: run docker compose to start project
  become: true
  become_user: "{{ mage_user_name }}"
  become_method: ansible.builtin.su
  community.docker.docker_compose_v2:
    project_src: "{{ project_dir }}"
    state: present
    profiles: run
    recreate: always
  environment:
    DOMAIN: "{{ letsencrypt_domain }}"

- name: generate script from template to reload nginx 
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.template:
    src: reload.sh
    dest: "/etc/cron.daily/reload-nginx.sh"
    owner: root
    group: root
    mode: '0755'
