---

- name: Manage packages
  ansible.builtin.include_tasks: packages.yml

- name: Manage users
  ansible.builtin.include_tasks: user.yml

# - name: Set up fail2ban
#   ansible.builtin.include_tasks: fail2ban.yml
