- name: Using apt package manager
  ansible.builtin.apt:
    name: "*"
    update_cache: true
  when: ansible_facts['os_family'] == "Debian"

- name: Using dnf package manager
  ansible.builtin.dnf:
    name: "*"
    update_cache: true
  when: ansible_facts['os_family'] == "RedHat"
