- name: create user "{{ project_user_name }}"
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.user:
    name: "{{ project_user_name }}"
    password: "{{ project_user_pass | password_hash('sha512') }}"
    shell: "{{ project_user_shell }}"
    create_home: true
    update_password: on_create
    groups: sudo
    append: true
  notify: Allow to use sudo

- name: add SSH key for user "{{ project_user_name }}"
  become: true
  become_user: "{{ project_user_name }}"
  become_method: ansible.builtin.su
  ansible.posix.authorized_key:
    user: "{{ project_user_name }}"
    key: "{{ project_user_key }}"
    state: present
