- name: Enable cron service
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.service:
    name: "{{ cron_service | default('crond') }}"
    state: started
    enabled: true

- name: Allow to use sudo
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    regexp: "^%sudo"
    line: "%sudo ALL=(ALL) ALL"
    validate: "/usr/sbin/visudo -cf %s"
