- name: Remove old versions
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - podman-docker
      - containerd
      - runc
    state: absent

- name: Download official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
    keyring: "{{ docker_keyfile }}"
    state: present

- name: Add apt repository
  ansible.builtin.apt_repository:
    repo: >
      deb [arch={{ cpu_arch | default('amd64') }}
      signed-by={{ docker_keyfile }}]
      https://download.docker.com/linux/debian
      {{ debian_release | default('bookworm') }} stable
    filename: docker
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  notify: Enable docker service
