- name: check if needed packages are installed
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: set permissions for keyrings directory
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: create file for GPG key
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.file:
    path: "{{ apt_docker_keyfile }}"
    state: touch
    mode: a+r
  changed_when: false
