- name: install firewall package
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  ansible.builtin.package:
    name:
      - "{{ ufw_pkg | default('ufw') }}"
    state: present
  notify: Enable firewall

- name: deny incoming traffic by default
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  community.general.ufw:
    default: deny
    direction: incoming
    protocol: any

- name: limit incoming traffic on port 22 (ssh)
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  community.general.ufw:
    rule: limit
    port: '22'
    direction: in
    protocol: tcp

- name: allow incoming traffic on ports 80, 443 (http, https)
  become: true
  become_user: root
  become_method: ansible.builtin.sudo
  community.general.ufw:
    rule: allow
    port: '{{ item }}'
    direction: in
    protocol: tcp
  loop:
    - '80'
    - '443'
